### ISSUE TITLE
Support Custom Token

### ISSUE THREAD

**Issue by 8d526** [polkaswitch/polkaswitch-ui#6]
Search/Add custom tokens (input = token address)

**Comment by davidkoller318** [comment]
@8d526 
Could you explain in detail ?

**Comment by renchuqiao** [comment]
When we search token by token address, if there is no such token, we should allow user to add custom token by token address. Something like
![image](https://user-images.githubusercontent.com/6487514/125854418-298567a2-535f-4c8e-9ee4-843477965ace.png)
![image](https://user-images.githubusercontent.com/6487514/125854476-232ab65b-17a1-41b5-9bbe-cce593a5476a.png)

**Comment by 8d526** [comment]
When we search token by token address, if there is no such token, we should allow user to add custom token by token address.

**Comment by chillvybz** [comment]
**Requirements:**

This is what you see when you type an unknown token or address:
![image](https://user-images.githubusercontent.com/85249140/125999768-8eeb1218-626a-42be-99d9-a8d2f8a292d3.png)

Please instead of the above UI show the following button/text:
![image](https://user-images.githubusercontent.com/85249140/126000773-9e055afa-d3d7-4e9f-aee6-14d6ffc757fb.png)

Clicking on the button, should launch a new overlay modal (like the Connect Modal), that looks like this:
![image](https://user-images.githubusercontent.com/85249140/126000854-299a671e-1351-4db4-b5ad-5249be4906ee.png)

Please ignore the Dark-Mode theme in the Mocks. Please keep the theme consistent with the same white-background theme.

Validating the token Address will require fetching the information directly from chain.
You will have to call DECIMALS() method and also verify that the token responds to ERC20 functions like BalanceOf().

TBD more mocks on Success and Failure screens.

**Comment by davidkoller318** [comment]
Okay.
